#eureka server服务端口
#server:
#  port: 9000
spring:
  application:
    name: gateWay # 应用名称，应用名称会在Eureka中作为服务名称
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080 #sentinel控制台监控
    inetutils:
      # 指定此客户端的ip
      default-ip-address: localhost
      #getway配置
      ##### 动态路由设置时，uri以 lb: //开头（lb代表从注册中⼼获取服务），后⾯是需要转发到的服务名称
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          lower-case-service-id: true
      routes: # 路由可以有多个
        - id: gateWay-router1 # 我们⾃定义的路由 ID，保持唯⼀
          # ⽬标服务地址 部署多实例） 动态路由：uri配置的应该是⼀个服务名称，⽽不应该是⼀个具体的服务实例的地址
          uri: lb://feignsentinel   #这里是要跳转到eureka服务下的名字地址
          # ⽬标服务地址 部署多实例） 动态路由：uri配置的应该是⼀个服务名称，⽽不应该是⼀个具体的服务实例的地址
          # gateway⽹关从服务注册中⼼获取实例信息然后负载后路由
          predicates: #断⾔：路由条件，Predicate 接受⼀个输⼊参数，返回⼀个布尔值结果。该接⼝包含多种默 认⽅法来将 Predicate 组合成其他复杂的逻辑（⽐如：与，或，⾮）。
            - Path=/demos/**  #配合过滤器使用 跳转到uri地址过滤前面的名字访问自己配置的路径名
          filters:
            - StripPrefix=0 #作用是转发请求前从请求中剥离的路径个数,0表示不剥离,1表示剥离一层。
#        - id: gateWay-router2 # 我们⾃定义的路由 ID，保持唯⼀
#          uri: lb://feignsentinel #服务名不要用下划线
#          predicates: #断⾔：路由条件，Predicate 接受⼀个输⼊参数，返回⼀个布尔值结果。该接⼝包含多种默 认⽅法来将 Predicate 组合成其他复杂的逻辑（⽐如：与，或，⾮）。
#            - Path=/feignsentinel/demos/**
#                #filters:
#                #- StripPrefix=1 #可以去掉url中的占位后转发路由 可以去掉demos后转发

#eureka配置
eureka:
  instance:
    hostname: gateWay  # 当前eureka实例的主机名
    ip-address: springcloud
  client:
    service-url:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      # 租约到期，服务时效时间，默认值90秒,服务超过90秒没有发⽣⼼跳，服务注册中心会将服务从列表移除
      lease-expiration-duration-in-seconds: 90
      # 配置客户端所交互的Eureka Server的地址（Eureka Server集群中每一个Server其实相对于其它Server来说都是Client）
      # 集群模式下，defaultZone应该指向其它Eureka Server，如果有更多其它Server实例，逗号拼接即可
      defaultZone: http://root:root@localhost:8077/eureka/  #http://127.0.0.1:8762/eureka # 注册到集群汇总，多个用,拼接
    register-with-eureka: true  # 集群模式下可以改成true
    fetch-registry: true # 集群模式下可以改成true
